# Source: https://github.com/serverless/examples/blob/master/aws-golang-http-get-post
service: smtpless

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x

package:
  individually: true

functions:
  mail:
    handler: smtpless
    events:
      - http:
          path: /
          method: post
    package:
      artifact: build/smtpless.zip
